import { chromium } from 'playwright';
const b = await chromium.launch({ headless: true, args: ['--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader'] });
const ctx = await b.newContext({ viewport: { width: 1500, height: 950 } });
const p = await ctx.newPage();
const skipTour = async () => { for (let i=0;i<4;i++){const s=p.locator('text=skip the tour').first(); if((await s.count())===0)break; await s.click({force:true,timeout:4000}).catch(()=>{}); await p.waitForTimeout(700);} };
const openBook = async () => { await p.locator('.shelf-a11y button').first().dispatchEvent('click'); await p.locator('.nb-leaf-paper').first().waitFor({state:'visible',timeout:40000}).catch(()=>{}); await p.waitForTimeout(2500); };
const skin = () => p.evaluate(() => document.getElementById('nb-ribbon-skin')?.textContent?.replace(/\s+/g,' ').slice(0,220) ?? 'NO SKIN ELEMENT');
await p.goto('http://localhost:1420?fx=force',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(9000); await skipTour(); await openBook();
console.log('default skin:', await skin());
await p.locator('.nb-rail-button[data-tool="ribbon-style"]').click({force:true});
await p.waitForTimeout(2500);
const label = await p.evaluate(() => { const panel=[...document.querySelectorAll('.nb-rail-panel')].find(e=>e.getAttribute('aria-hidden')==='false'); const t=[...panel.querySelectorAll('.nb-strip-tile')].filter(x=>!x.classList.contains('is-active')&&!x.classList.contains('nb-strip-more'))[4]; t?.click(); return t?.getAttribute('title')??t?.textContent?.trim(); });
await p.waitForTimeout(2500);
console.log('picked:', label);
const before = await skin();
console.log('after pick :', before);
await p.reload({waitUntil:'domcontentloaded'}); await p.waitForTimeout(9000); await skipTour(); await openBook();
const after = await skin();
console.log('after reload:', after);
console.log('PERSISTS:', before === after);
await b.close();
