/**
 * Serializable domain contracts for Alcove's notebook agent.
 *
 * This file deliberately contains no Solid, editor, database, provider SDK or
 * LangGraph objects. A graph checkpoint may contain these values; it must never
 * contain an API key, attachment bytes, AbortSignal, editor instance, database
 * handle, or an image data URL.
 */
import type { PageDoc } from '../../data/types';
import type { AgentTextPrivacyReceipt } from './textPrivacy';

export const AGENT_STATE_VERSION = 1 as const;

export type AgentStateVersion = typeof AGENT_STATE_VERSION;
export type IsoTimestamp = string;
export type AgentJsonPrimitive = string | number | boolean | null;
export type AgentJsonValue =
  | AgentJsonPrimitive
  | { readonly [key: string]: AgentJsonValue }
  | readonly AgentJsonValue[];

export type AgentLifecycle =
  | 'idle'
  | 'running'
  | 'waiting_for_user'
  | 'waiting_for_preview_decision'
  | 'cancelled'
  | 'failed'
  | 'completed';

export type AgentPhase =
  | 'intake'
  | 'reading_sources'
  | 'planning'
  | 'drafting'
  | 'checking_script'
  | 'rendering_preview'
  | 'reviewing_preview'
  | 'repairing'
  | 'building_preview'
  | 'waiting_for_user'
  | 'waiting_for_preview_decision'
  | 'finished';

export interface AgentRunIdentity {
  readonly threadId: string;
  readonly taskId: string;
  readonly runId: string;
  readonly bookId: string;
}

export interface AgentTaskBrief {
  readonly goal: string;
  readonly desiredOutcome?: string;
  readonly audience?: string;
  readonly depth?: string;
  readonly length?: string;
  readonly creativeDirection?: string;
  readonly defaultContextPolicy: AgentContextPolicy;
  readonly assumptions: readonly string[];
  readonly preserveAllSourceInformation: boolean;
}

export type AgentContextPolicy =
  | 'selection_and_page'
  | 'current_page'
  | 'nearby_pages'
  | 'whole_book'
  | 'explicit_only';

export interface AgentPlanStep {
  readonly id: string;
  readonly title: string;
  readonly description?: string;
  readonly status: 'pending' | 'in_progress' | 'completed' | 'blocked';
  readonly sourceUnitIds?: readonly string[];
}

export interface AgentPlan {
  readonly version: number;
  readonly summary: string;
  readonly steps: readonly AgentPlanStep[];
  /** Material-work checkpoint this plan describes; excludes wording and clocks. */
  readonly workFingerprint?: string;
  readonly createdAt: IsoTimestamp;
  readonly updatedAt: IsoTimestamp;
}

export type ConversationRole = 'user' | 'assistant';

/** Only user-visible conversation is kept here. Hidden reasoning has no field. */
export interface AgentConversationMessage {
  readonly id: string;
  readonly role: ConversationRole;
  readonly text: string;
  readonly createdAt: IsoTimestamp;
  readonly citations?: readonly SourceCitation[];
}

/**
 * A deliberately empty image destination authored into Notebook Script.
 * `slotId` is deterministic only within the draft whose hash owns it; a new
 * draft invalidates the complete handoff instead of guessing across edits.
 */
export interface PortableImageSlot {
  readonly slotId: string;
  readonly pageNumber: number;
  readonly ordinal: number;
  readonly alt: string;
  readonly placeholder: string;
  readonly caption?: string;
  readonly frame?: string;
  readonly displayWidthPercent?: number;
}

export type ImageGenerationRole =
  | 'hero'
  | 'explanatory_diagram'
  | 'concept_illustration'
  | 'analogy_scene'
  | 'reference'
  | 'decorative';

export type ImageGenerationAspect =
  | 'square_1_1'
  | 'landscape_4_3'
  | 'landscape_3_2'
  | 'wide_16_9'
  | 'portrait_4_5'
  | 'portrait_3_4'
  | 'banner_3_1';

/** A ready-to-copy prompt for one exact portable image slot. */
export interface ImageGenerationPrompt {
  readonly id: string;
  readonly slot: PortableImageSlot;
  readonly role: ImageGenerationRole;
  readonly aspect: ImageGenerationAspect;
  readonly widthPx: number;
  readonly heightPx: number;
  readonly prompt: string;
  readonly avoid?: string;
}

/**
 * Durable, provider-neutral companion to a draft. It contains instructions,
 * never generated bytes, and remains useful after the reviewed pages are
 * inserted so the reader can fill the portable slots in any image platform.
 */
export interface ImagePromptHandoff {
  readonly draftHash: string;
  readonly prompts: readonly ImageGenerationPrompt[];
  readonly createdAt: IsoTimestamp;
}

export interface AgentModelToolCall {
  readonly id: string;
  readonly name: string;
  readonly arguments: AgentJsonValue;
}

export interface AgentModelUserTurn {
  readonly id: string;
  readonly role: 'user';
  readonly content: string;
  readonly createdAt: IsoTimestamp;
}

export interface AgentModelAssistantTurn {
  readonly id: string;
  readonly role: 'assistant';
  /** User-facing prose only. Reasoning summaries are not accepted here. */
  readonly content: string;
  /** Provider-authored tool plan required for Cohere tool-call continuity. */
  readonly toolPlan?: string;
  readonly toolCalls: readonly AgentModelToolCall[];
  readonly createdAt: IsoTimestamp;
}

export interface AgentModelToolTurn {
  readonly id: string;
  readonly role: 'tool';
  readonly toolCallId: string;
  readonly toolName: string;
  readonly content: AgentJsonValue;
  readonly isError: boolean;
  /** Opaque rendered/source images intentionally attached to the next model turn. */
  readonly imageRefs?: readonly AgentImageRef[];
  readonly imagePurpose?: 'source_analysis' | 'draft_visual_review';
  readonly createdAt: IsoTimestamp;
}

export type AgentModelTurn =
  | AgentModelUserTurn
  | AgentModelAssistantTurn
  | AgentModelToolTurn;

export type SourceKind =
  | 'notebook'
  | 'page'
  | 'selection'
  | 'text'
  | 'pdf'
  | 'image'
  | 'notebook_script_spec';

/**
 * Durable, byte-free ownership references for sources queued for ingestion.
 * Keeping this domain type here lets AgentState survive a failed/restarted
 * intake without depending on the runtime adapter module.
 */
export type SourceAttachmentRef =
  | {
      readonly kind: 'managed_asset';
      readonly assetId: string;
      readonly title: string;
      readonly mediaType: string;
      readonly digest: string;
    }
  | {
      readonly kind: 'notebook_book';
      readonly bookId: string;
      readonly title: string;
    }
  | {
      readonly kind: 'notebook_page';
      readonly pageId: string;
      readonly title: string;
    }
  | {
      readonly kind: 'notebook_selection';
      readonly pageId: string;
      readonly selectionDigest: string;
      readonly title: string;
    }
  | {
      readonly kind: 'canonical_spec';
      readonly sectionIds?: readonly string[];
      readonly title: string;
    };

export interface SourceAnchor {
  readonly sourceId: string;
  readonly unitId: string;
  readonly pageNumber?: number;
  readonly figure?: string;
  readonly start?: number;
  readonly end?: number;
  readonly pageId?: string;
  readonly blockId?: string;
}

export interface SourceUnitDescriptor {
  readonly id: string;
  readonly label: string;
  readonly ordinal: number;
  readonly digest: string;
  readonly estimatedTokens: number;
  readonly characters: number;
  readonly hasText: boolean;
  readonly hasVisual: boolean;
  /**
   * `unresolved` is a hard coverage blocker: the source says this unit carries
   * visual evidence, but Alcove could not expose trustworthy managed pixels.
   * Omitted means the older/non-visual `none` behavior.
   */
  readonly visualEvidence?: 'none' | 'available' | 'unresolved';
  readonly anchor: SourceAnchor;
}

export interface AgentSourceDescriptor {
  readonly id: string;
  readonly title: string;
  readonly kind: SourceKind;
  readonly digest: string;
  readonly mediaType: string;
  readonly estimatedTokens: number;
  readonly byteSize?: number;
  readonly extractionQuality?: 'good' | 'partial' | 'weak' | 'visual_only';
  readonly quarantined: boolean;
  readonly promptInjectionWarnings: readonly string[];
  readonly units: readonly SourceUnitDescriptor[];
}

export interface SourceManifest {
  readonly version: number;
  readonly createdAt: IsoTimestamp;
  readonly sources: readonly AgentSourceDescriptor[];
  readonly totalEstimatedTokens: number;
  readonly digest: string;
}

export interface SourceRead {
  readonly sourceId: string;
  readonly sourceDigest: string;
  readonly units: readonly {
    readonly unitId: string;
    readonly anchor: SourceAnchor;
    readonly text: string;
    readonly digest: string;
  }[];
  readonly truncated: boolean;
  readonly nextUnitId?: string;
  /** Units whose text was readable but whose required pixels remain unavailable. */
  readonly unresolvedVisualUnitIds?: readonly string[];
  /** Rendered source pages/figures for multimodal analysis, never raw bytes. */
  readonly visualRefs?: readonly {
    readonly image: AgentImageRef;
    readonly anchor: SourceAnchor;
    readonly label: string;
    /**
     * Exact library-relative asset identity when this visual is a reader
     * attachment that may be placed in Notebook Script. PDF render evidence
     * deliberately has no portable path: it is analysis material, not a
     * reader-supplied picture to silently copy into the book.
     */
    readonly portableAssetPath?: string;
  }[];
}

export interface SourceCitation {
  readonly sourceId: string;
  readonly sourceTitle: string;
  readonly unitId: string;
  readonly label: string;
  readonly pageNumber?: number;
  readonly figure?: string;
  readonly excerpt?: string;
}

export type RetrievalStrategy = 'direct' | 'rag' | 'complete_sweep';

export interface AdaptiveRetrievalPlan {
  readonly strategy: RetrievalStrategy;
  readonly rationale: string;
  readonly sourceIds: readonly string[];
  readonly estimatedInputTokens: number;
  readonly directContextBudget: number;
  readonly query?: string;
  readonly candidateLimit?: number;
  readonly rerankLimit?: number;
  readonly sweepBatchUnits?: number;
  readonly requiresCompleteCoverage: boolean;
}

export interface RetrievalHit {
  readonly sourceId: string;
  readonly unitId: string;
  readonly anchor: SourceAnchor;
  readonly text: string;
  readonly digest: string;
  readonly lexicalScore?: number;
  readonly semanticScore?: number;
  readonly rerankScore?: number;
}

export interface SourceCoverageLedger {
  readonly manifestDigest: string;
  readonly mode: 'relevant' | 'complete';
  readonly requiredUnitIds: readonly string[];
  readonly readUnitIds: readonly string[];
  /**
   * Earliest provider turn whose tool result exposed each readable unit. A
   * later provider turn is required before that unit may authorize a citation
   * or final proposal; parallel tools in one assistant batch do not count as
   * model observation.
   */
  readonly readExposures?: readonly {
    readonly unitId: string;
    readonly providerCallCount: number;
    readonly exposedAt: IsoTimestamp;
  }[];
  readonly citedUnitIds: readonly string[];
  readonly omittedUnitIds: readonly string[];
  readonly staleSourceIds: readonly string[];
  readonly complete: boolean;
  readonly updatedAt: IsoTimestamp;
}

export type NotebookInsertionTarget =
  | { readonly kind: 'caret'; readonly pageId: string; readonly position: number }
  | {
      readonly kind: 'replace_selection';
      readonly pageId: string;
      readonly from: number;
      readonly to: number;
      readonly selectionDigest: string;
    }
  | { readonly kind: 'before_page'; readonly pageId: string }
  | { readonly kind: 'after_page'; readonly pageId: string }
  | { readonly kind: 'book_start' }
  | { readonly kind: 'book_end' }
  | { readonly kind: 'new_pages'; readonly afterPageId?: string };

export interface NotebookSnapshotRef {
  readonly bookId: string;
  readonly bookRevision: string;
  readonly pageIds: readonly string[];
  readonly pageRevisions: Readonly<Record<string, string>>;
  readonly capturedAt: IsoTimestamp;
}

export interface NotebookPageInspection {
  readonly pageId: string;
  readonly ordinal: number;
  readonly revision: string;
  readonly title?: string;
  readonly plainText: string;
  readonly scriptSource?: string;
  readonly documentDigest: string;
  /**
   * Exact editor JSON captured with `revision` and `documentDigest`.
   *
   * Production includes it so the disposable renderer can preview a caret or
   * selection edit in its real surrounding page. Tool results deliberately
   * omit this duplicate body and continue exposing `scriptSource` to the
   * model. Optional keeps provider/test adapters source-compatible.
   */
  readonly document?: PageDoc;
}

export interface NotebookSelectionInspection {
  readonly pageId: string;
  readonly blockIds: readonly string[];
  readonly from: number;
  readonly to: number;
  readonly text: string;
  readonly selectionDigest: string;
  readonly pageRevision: string;
}

export interface NotebookScriptDiagnostic {
  readonly severity: 'warning' | 'error';
  readonly code: string;
  readonly message: string;
  readonly line?: number;
  readonly column?: number;
  readonly pageNumber?: number;
}

export interface NotebookScriptValidation {
  readonly draftHash: string;
  readonly parserDiagnostics: readonly NotebookScriptDiagnostic[];
  readonly staticDiagnostics: readonly NotebookScriptDiagnostic[];
  readonly imageDiagnostics: readonly NotebookScriptDiagnostic[];
  readonly pageLedgerDiagnostics: readonly NotebookScriptDiagnostic[];
  readonly valid: boolean;
  readonly checkedAt: IsoTimestamp;
}

export interface NotebookDraft {
  readonly runId: string;
  readonly version: number;
  readonly script: string;
  readonly draftHash: string;
  readonly sourceManifestDigest?: string;
  readonly createdAt: IsoTimestamp;
}

/**
 * Local-only finalization produced after the model has reviewed the masked
 * native renders. The restored script is revalidated and rerendered without a
 * provider hop; this exact generation and receipt are what the reader previews
 * and what approval later applies.
 */
export interface AgentLocalRestoredFinal {
  readonly maskedDraftHash: string;
  readonly draft: NotebookDraft;
  readonly validation: NotebookScriptValidation;
  readonly previewGeneration: DraftPreviewGeneration;
  readonly imagePromptHandoff?: ImagePromptHandoff;
  readonly finalizedAt: IsoTimestamp;
}

/** Opaque resource reference resolved by the Rust/provider gateway, never bytes. */
export interface AgentImageRef {
  readonly resourceId: string;
  readonly mimeType: 'image/png' | 'image/jpeg' | 'image/webp';
  readonly digest: string;
  readonly width: number;
  readonly height: number;
}

export interface DraftPreviewPage {
  readonly pageId: string;
  readonly pageNumber: number;
  readonly width: number;
  readonly height: number;
  readonly image: AgentImageRef;
  readonly textDigest: string;
  readonly layoutDigest: string;
  readonly sourceStart?: number;
  readonly sourceEnd?: number;
  /**
   * Normal fixed-page pagination moved trailing blocks onto a generated leaf.
   * This is resolved flow, not a layout failure.
   */
  readonly paginationSpill: boolean;
  /** Content still exceeded the fixed leaf after the pagination drain settled. */
  readonly residualOverflow: boolean;
}

export interface DraftPreviewGeneration {
  readonly generationId: string;
  readonly draftHash: string;
  readonly layoutHash: string;
  readonly rendererVersion: string;
  readonly bookSnapshotRevision: string;
  readonly createdAt: IsoTimestamp;
  readonly parserValid: boolean;
  readonly layoutValid: boolean;
  readonly stale: boolean;
  readonly pageCount: number;
  readonly pages: readonly DraftPreviewPage[];
  readonly diagnostics: readonly NotebookScriptDiagnostic[];
}

export type VisualFindingCategory =
  | 'overflow'
  | 'clipping'
  | 'collision'
  | 'illegible'
  | 'empty_page'
  | 'bad_break'
  | 'missing_media'
  | 'duplication'
  | 'visual_hierarchy'
  | 'other';

export interface DraftVisualFinding {
  readonly id: string;
  readonly generationId: string;
  readonly pageId: string;
  readonly severity: 'info' | 'warning' | 'blocking';
  readonly category: VisualFindingCategory;
  readonly summary: string;
  /** A concise observable explanation, never hidden chain-of-thought. */
  readonly evidence?: string;
  readonly resolved: boolean;
}

/**
 * Receipt written only by `read_draft_preview_pages` when the exact current
 * rendered image is attached to a provider-visible tool turn. A page name by
 * itself is not evidence that its pixels were inspected.
 */
export interface DraftPreviewImageExposure {
  readonly generationId: string;
  readonly pageId: string;
  readonly imageResourceId: string;
  readonly imageDigest: string;
  readonly layoutDigest: string;
  /** Provider turn that requested the image read; review must be a later turn. */
  readonly readRequestedAtProviderCall: number;
  readonly exposedAt: IsoTimestamp;
}

export interface DraftVisualReviewLedger {
  readonly generationId: string;
  readonly draftHash: string;
  readonly requiredPageIds: readonly string[];
  readonly imageExposures: readonly DraftPreviewImageExposure[];
  readonly inspectedPageIds: readonly string[];
  readonly findings: readonly DraftVisualFinding[];
  readonly complete: boolean;
  readonly passed: boolean;
  readonly updatedAt: IsoTimestamp;
}

export interface UserPreviewContract {
  readonly previewId: string;
  readonly generationId: string;
  readonly draftHash: string;
  readonly layoutHash: string;
  readonly bookId: string;
  readonly expectedBookRevision: string;
  /**
   * Exact inspected order. Current pages may add a trailing blank suffix, but
   * every inspected page must remain the same ordered prefix at apply time.
   */
  readonly expectedPageIds?: readonly string[];
  readonly insertionTarget: NotebookInsertionTarget;
  readonly expectedPageCount: number;
  readonly pages: readonly DraftPreviewPage[];
  readonly assumptions: readonly string[];
  readonly citations: readonly SourceCitation[];
  readonly imageGenerationPrompts: readonly ImageGenerationPrompt[];
  readonly sourceCoverage: SourceCoverageLedger;
  readonly visualReview: DraftVisualReviewLedger;
  readonly validation: NotebookScriptValidation;
}

export type PatchProposalStatus =
  | 'draft'
  | 'waiting_for_approval'
  | 'approved_pending_apply'
  | 'apply_failed'
  | 'applied'
  /** Legacy pre-finalize checkpoints are treated as pending apply. */
  | 'approved'
  | 'rejected';

/**
 * A proposal, never a mutation command. BookView's future apply service must
 * independently re-check the revision and consume the idempotency key.
 */
export interface NotebookPatchProposal {
  readonly patchId: string;
  readonly idempotencyKey: string;
  readonly runId: string;
  readonly draftVersion: number;
  readonly draftHash: string;
  readonly script: string;
  readonly expectedBookRevision: string;
  readonly expectedPageIds?: readonly string[];
  readonly insertionTarget: NotebookInsertionTarget;
  readonly preview: UserPreviewContract;
  readonly status: PatchProposalStatus;
  readonly createdAt: IsoTimestamp;
}

export interface AgentToolBudget {
  readonly maxProviderCalls: number;
  readonly maxToolCalls: number;
  readonly maxRepairPasses: number;
  readonly maxProviderRetries: number;
  readonly maxSourceCharactersPerToolResult: number;
}

export interface AgentUsage {
  readonly providerCalls: number;
  readonly toolCalls: number;
  readonly repairPasses: number;
  readonly providerRetries: number;
  readonly inputTokens: number;
  readonly outputTokens: number;
}

/**
 * Durable baselines for the current reader-authored turn. Usage itself stays
 * monotonic because source-observation ledgers use the cumulative provider
 * call count as an epoch; policy subtracts these baselines when enforcing the
 * per-turn provider/tool budgets.
 *
 * The field on AgentState is optional so checkpoints written before budget
 * windows existed naturally behave as the initial zero-based window.
 */
export interface AgentBudgetWindow {
  readonly providerCallsAtStart: number;
  readonly toolCallsAtStart: number;
  readonly repairPassesAtStart?: number;
  readonly startedAt: IsoTimestamp;
  readonly readerMessageId?: string;
}

export interface AgentRetryState {
  readonly attempt: number;
  readonly lastStatus?: number;
  readonly retryAt?: IsoTimestamp;
  readonly lastMessage?: string;
}

export interface AgentCancellationState {
  readonly requested: boolean;
  readonly requestedAt?: IsoTimestamp;
  readonly reason?: string;
  readonly lastSafeCheckpointStep: number;
}

export interface AgentPublicError {
  readonly code:
    | 'provider_auth'
    | 'provider_rate_limit'
    | 'provider_unavailable'
    | 'provider_invalid_response'
    | 'tool_error'
    | 'budget_exhausted'
    | 'cancelled'
    | 'stale_context'
    | 'policy_blocked'
    | 'internal';
  readonly message: string;
  readonly retryable: boolean;
  readonly status?: number;
}

/**
 * Durable forensic receipt for the most recent local BookView apply failure.
 * `lastError` is intentionally cleared when recovery begins; this receipt is
 * not, so a later copied diagnostic still contains the error that caused the
 * original Insert click to fail.
 */
export interface AgentApplyFailureReceipt {
  readonly patchId: string;
  readonly previewId: string;
  readonly message: string;
  readonly failedAt: IsoTimestamp;
}

export interface AgentState {
  readonly schemaVersion: AgentStateVersion;
  readonly identity: AgentRunIdentity;
  readonly lifecycle: AgentLifecycle;
  readonly phase: AgentPhase;
  readonly taskBrief: AgentTaskBrief;
  readonly conversation: readonly AgentConversationMessage[];
  readonly modelHistory: readonly AgentModelTurn[];
  /**
   * Reader follow-ups written while recovering a stopped turn. They are
   * visible in the conversation immediately, but enter provider history only
   * at the next model boundary. This keeps Cohere's assistant/tool-result
   * continuity valid when Stop happened between sibling tool calls.
   */
  readonly pendingUserTurns?: readonly AgentModelUserTurn[];
  readonly plan?: AgentPlan;
  readonly notebookSnapshot?: NotebookSnapshotRef;
  /** Cleared only after the complete initial manifest has been committed. */
  readonly pendingSourceAttachments?: readonly SourceAttachmentRef[];
  readonly sourceManifest?: SourceManifest;
  readonly retrievalPlan?: AdaptiveRetrievalPlan;
  readonly sourceCoverage?: SourceCoverageLedger;
  readonly draft?: NotebookDraft;
  readonly validation?: NotebookScriptValidation;
  readonly previewGeneration?: DraftPreviewGeneration;
  readonly visualReview?: DraftVisualReviewLedger;
  readonly insertionTarget?: NotebookInsertionTarget;
  readonly patchProposal?: NotebookPatchProposal;
  readonly imagePromptHandoff?: ImagePromptHandoff;
  /**
   * Local-only reversible text substitutions. Once present, privacy remains
   * enabled for this task through retries and restart even if the global
   * preference changes.
   */
  readonly textPrivacy?: AgentTextPrivacyReceipt;
  readonly localRestoredFinal?: AgentLocalRestoredFinal;
  readonly pendingToolCalls: readonly AgentModelToolCall[];
  readonly budget: AgentToolBudget;
  readonly usage: AgentUsage;
  readonly budgetWindow?: AgentBudgetWindow;
  readonly retry: AgentRetryState;
  readonly cancellation: AgentCancellationState;
  readonly lastError?: AgentPublicError;
  readonly lastApplyFailure?: AgentApplyFailureReceipt;
  readonly checkpointStep: number;
  readonly createdAt: IsoTimestamp;
  readonly updatedAt: IsoTimestamp;
}

export interface AskUserQuestion {
  readonly id: string;
  readonly prompt: string;
  readonly whyItMatters?: string;
  readonly choices?: readonly { readonly id: string; readonly label: string }[];
  /** A concrete default the reader may accept; absent means input is essential. */
  readonly sensibleDefault?: string;
  readonly allowFreeText: boolean;
}

export type AgentInterrupt =
  | {
      readonly kind: 'requirements';
      readonly title: string;
      readonly questions: readonly AskUserQuestion[];
      readonly allowSensibleDefaults: boolean;
      /** Durable assistant bubble that owns this otherwise-hidden pause. */
      readonly messageId?: string;
    }
  | {
      readonly kind: 'blocker';
      readonly title: string;
      readonly message: string;
      readonly recoveryChoices?: readonly string[];
    }
  | {
      readonly kind: 'final_preview';
      readonly title: string;
      readonly preview: UserPreviewContract;
      readonly decisions: readonly ['approve', 'reject', 'feedback', 'change_location'];
    };

export type AgentResumeValue =
  | {
      readonly kind: 'requirements_answer';
      /** Exact free-form reader reply. New flows use this field exclusively. */
      readonly response?: string;
      /** Reuses the optimistic panel message instead of emitting a duplicate. */
      readonly userMessageId?: string;
      /** Legacy structured-answer payload retained for restoring old tasks. */
      readonly answers?: Readonly<Record<string, string>>;
      readonly useSensibleDefaults?: boolean;
      /** Exact unanswered questions for which the reader accepted the proposed default. */
      readonly defaultQuestionIds?: readonly string[];
    }
  | {
      readonly kind: 'blocker_answer';
      readonly response: string;
      readonly userMessageId?: string;
    }
  | {
      readonly kind: 'preview_decision';
      readonly decision: 'approve' | 'reject' | 'feedback' | 'change_location';
      readonly feedback?: string;
      readonly insertionTarget?: NotebookInsertionTarget;
      readonly previewId: string;
    };

interface AgentActivityBase {
  readonly id: string;
  readonly sequence: number;
  readonly threadId: string;
  readonly taskId: string;
  readonly runId: string;
  readonly at: IsoTimestamp;
}

export type AgentActivityEvent =
  | (AgentActivityBase & {
      readonly type: 'run.started';
      readonly goal: string;
    })
  | (AgentActivityBase & {
      readonly type: 'status.changed';
      readonly phase: AgentPhase;
      readonly summary: string;
    })
  | (AgentActivityBase & {
      readonly type: 'plan.updated';
      readonly plan: AgentPlan;
    })
  | (AgentActivityBase & {
      readonly type: 'user.message' | 'assistant.message';
      readonly message: AgentConversationMessage;
    })
  | (AgentActivityBase & {
      readonly type: 'tool.started';
      readonly toolCallId: string;
      readonly toolName: string;
      readonly summary: string;
    })
  | (AgentActivityBase & {
      readonly type: 'tool.completed';
      readonly toolCallId: string;
      readonly toolName: string;
      readonly summary: string;
    })
  | (AgentActivityBase & {
      readonly type: 'tool.failed';
      readonly toolCallId: string;
      readonly toolName: string;
      readonly message: string;
    })
  | (AgentActivityBase & {
      readonly type: 'source.coverage';
      readonly ledger: SourceCoverageLedger;
    })
  | (AgentActivityBase & {
      readonly type: 'source.ingestion';
      readonly phase: 'hashing' | 'extracting' | 'quarantining' | 'indexing';
      readonly completed: number;
      readonly total: number;
      readonly summary: string;
    })
  | (AgentActivityBase & {
      readonly type: 'draft.updated';
      readonly draftVersion: number;
      readonly draftHash: string;
      readonly reason: 'initial' | 'repair' | 'user_feedback';
    })
  | (AgentActivityBase & {
      readonly type: 'preview.rendering';
      readonly draftHash: string;
    })
  | (AgentActivityBase & {
      readonly type: 'preview.ready';
      readonly generation: DraftPreviewGeneration;
    })
  | (AgentActivityBase & {
      readonly type: 'preview.page_inspected';
      readonly generationId: string;
      readonly pageId: string;
      readonly pageNumber: number;
    })
  | (AgentActivityBase & {
      readonly type: 'preview.visual_finding';
      readonly finding: DraftVisualFinding;
    })
  | (AgentActivityBase & {
      readonly type: 'approval.requested';
      readonly preview: UserPreviewContract;
    })
  | (AgentActivityBase & {
      readonly type: 'retry.scheduled';
      readonly attempt: number;
      readonly delayMs: number;
      readonly summary: string;
    })
  | (AgentActivityBase & {
      readonly type: 'run.cancelled';
      readonly reason: string;
    })
  | (AgentActivityBase & {
      readonly type: 'run.completed';
      readonly summary: string;
      readonly patchId?: string;
    })
  | (AgentActivityBase & {
      readonly type: 'run.failed';
      readonly error: AgentPublicError;
    });

export interface AgentRunResult {
  readonly state: AgentState;
  readonly interrupt?: AgentInterrupt;
}

export const DEFAULT_AGENT_BUDGET: AgentToolBudget = {
  // The mandatory no-repair workflow already needs roughly nine observation
  // boundaries (inspect, read, draft, validate, render, see pixels, record,
  // propose, submit). Leave enough room for multi-batch page inspection and
  // several honest repair generations while keeping retries and final writes
  // independently bounded and reader-approved.
  maxProviderCalls: 24,
  maxToolCalls: 96,
  maxRepairPasses: 4,
  maxProviderRetries: 3,
  maxSourceCharactersPerToolResult: 48_000,
};

export function createInitialAgentState(input: {
  readonly identity: AgentRunIdentity;
  readonly goal: string;
  readonly desiredOutcome?: string;
  readonly creativeDirection?: string;
  readonly defaultContextPolicy?: AgentContextPolicy;
  readonly preserveAllSourceInformation?: boolean;
  readonly budget?: Partial<AgentToolBudget>;
  readonly now: IsoTimestamp;
  readonly userMessageId: string;
}): AgentState {
  const taskBrief: AgentTaskBrief = {
    goal: input.goal,
    desiredOutcome: input.desiredOutcome,
    creativeDirection: input.creativeDirection,
    defaultContextPolicy: input.defaultContextPolicy ?? 'selection_and_page',
    assumptions: [],
    preserveAllSourceInformation: input.preserveAllSourceInformation ?? false,
  };
  const initialMessage: AgentConversationMessage = {
    id: input.userMessageId,
    role: 'user',
    text: input.goal,
    createdAt: input.now,
  };
  return {
    schemaVersion: AGENT_STATE_VERSION,
    identity: input.identity,
    lifecycle: 'idle',
    phase: 'intake',
    taskBrief,
    conversation: [initialMessage],
    modelHistory: [
      {
        id: input.userMessageId,
        role: 'user',
        content: input.goal,
        createdAt: input.now,
      },
    ],
    pendingToolCalls: [],
    budget: { ...DEFAULT_AGENT_BUDGET, ...input.budget },
    usage: {
      providerCalls: 0,
      toolCalls: 0,
      repairPasses: 0,
      providerRetries: 0,
      inputTokens: 0,
      outputTokens: 0,
    },
    budgetWindow: {
      providerCallsAtStart: 0,
      toolCallsAtStart: 0,
      repairPassesAtStart: 0,
      startedAt: input.now,
      readerMessageId: input.userMessageId,
    },
    retry: { attempt: 0 },
    cancellation: { requested: false, lastSafeCheckpointStep: 0 },
    checkpointStep: 0,
    createdAt: input.now,
    updatedAt: input.now,
  };
}
