import { chromium } from 'playwright';
import { readFileSync, writeFileSync } from 'node:fs';
const [bodyFile, outPath, pick] = process.argv.slice(2);
const body = readFileSync(bodyFile, 'utf8');
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1200, height: 800 } });
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
await page.goto('http://127.0.0.1:1497/qa/mat/lab.html', { waitUntil: 'load', timeout: 120000 });
await page.waitForFunction(() => globalThis.__labReady === true, null, { timeout: 120000 });
await page.evaluate((p)=>{ globalThis.__pick = p; }, pick ?? '[0,1,2,3]');
const url = await page.evaluate(new Function(`return (async () => { ${body} })()`));
writeFileSync(outPath, Buffer.from(url.split(',')[1], 'base64'));
await browser.close(); console.log('wrote', outPath);
