/**
 * src/views/rail/StickersPanel.tsx — 8-sticker grid + block-effect
 * quick-apply buttons, both driving the live page through src/editor's
 * active-editor registry.
 *
 * Stickers insert via the editor's `insertSticker` command (sticker node,
 * src/editor/nodes/sticker.tsx). Effects toggle the universal block-effect
 * attributes (src/editor/effects/blockEffects.ts) on the top-level block
 * under the caret via tr.setNodeAttribute — clicking an already-applied
 * effect clears it.
 */
import { For, type JSX } from 'solid-js';
import { NodeSelection } from '@tiptap/pm/state';
import { activeEditor } from '../../editor/insert/activeEditor';
import { STICKER_IDS, stickerSvg, type StickerId } from '../../editor/nodes/stickers';

interface EffectAction {
  readonly label: string;
  readonly key: string;
  readonly value: string | number;
}

const EFFECTS: readonly EffectAction[] = [
  { label: 'tilt left', key: 'rotate', value: -2 },
  { label: 'tilt right', key: 'rotate', value: 2 },
  { label: 'tape', key: 'tape', value: 'top' },
  { label: 'washi strip', key: 'washi', value: 'top' },
  { label: 'soft shadow', key: 'shadow', value: 'soft' },
  { label: 'scallop frame', key: 'frame', value: 'scallop' },
  { label: 'stitch frame', key: 'frame', value: 'stitch' },
  { label: 'torn paper', key: 'paper', value: 'torn' },
  { label: 'squiggle line', key: 'underline', value: 'squiggle' },
  { label: 'marker line', key: 'underline', value: 'marker' },
];

const EFFECT_KEYS = ['rotate', 'tape', 'washi', 'shadow', 'frame', 'paper', 'underline'];

/** Position of the top-level block under the selection, or null. */
function topBlockPos(): { pos: number; attrs: Record<string, unknown> } | null {
  const editor = activeEditor();
  if (!editor) return null;
  const sel = editor.state.selection;
  if (sel instanceof NodeSelection && sel.$from.depth === 0) {
    return { pos: sel.from, attrs: sel.node.attrs as Record<string, unknown> };
  }
  if (sel.$from.depth < 1) return null;
  const pos = sel.$from.before(1);
  const node = editor.state.doc.nodeAt(pos);
  if (!node) return null;
  return { pos, attrs: node.attrs as Record<string, unknown> };
}

export default function StickersPanel(): JSX.Element {
  const insertSticker = (stickerId: StickerId): void => {
    const editor = activeEditor();
    if (!editor) return;
    editor.chain().focus().insertSticker({ stickerId }).run();
  };

  const toggleEffect = (action: EffectAction): void => {
    const editor = activeEditor();
    const target = topBlockPos();
    if (!editor || !target) return;
    const current = target.attrs[action.key];
    const next = current === action.value ? null : action.value;
    editor.view.dispatch(
      editor.state.tr.setNodeAttribute(target.pos, action.key, next),
    );
  };

  const clearEffects = (): void => {
    const editor = activeEditor();
    const target = topBlockPos();
    if (!editor || !target) return;
    let tr = editor.state.tr;
    for (const key of EFFECT_KEYS) {
      if (target.attrs[key] != null) {
        tr = tr.setNodeAttribute(target.pos, key, null);
      }
    }
    if (tr.docChanged) editor.view.dispatch(tr);
  };

  return (
    <div class="nb-stickers">
      <section class="nb-panel-section">
        <h3 class="nb-panel-section-title">stickers</h3>
        <div class="nb-sticker-grid" role="group" aria-label="Stickers">
          <For each={STICKER_IDS}>
            {(id) => (
              <button
                type="button"
                class="nb-sticker-button"
                aria-label={`${id} sticker`}
                data-tip={id}
                onClick={() => insertSticker(id)}
                // eslint-disable-next-line solid/no-innerhtml -- trusted
                // deterministic markup generated by our own stickerSvg.
                innerHTML={stickerSvg(id)}
              />
            )}
          </For>
        </div>
        <p class="nb-panel-footnote">drops in at your cursor</p>
      </section>

      <section class="nb-panel-section nb-panel-section-divided">
        <h3 class="nb-panel-section-title">block effects</h3>
        <div class="nb-chip-grid" role="group" aria-label="Block effects">
          <For each={EFFECTS}>
            {(effect) => (
              <button
                type="button"
                class="nb-chip"
                onClick={() => toggleEffect(effect)}
              >
                {effect.label}
              </button>
            )}
          </For>
          <button type="button" class="nb-chip nb-chip-ghost" onClick={clearEffects}>
            clear effects
          </button>
        </div>
        <p class="nb-panel-footnote">
          dresses the block your cursor is on — click again to undo
        </p>
      </section>
    </div>
  );
}
